apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: cloudnative-pg
    namespace: cloudnative-pg
spec:
    interval: 5m
    chart:
        spec:
            # renovate: registryUrl=https://charts.truecharts.org
            chart: cloudnative-pg
            version: v1.8.0
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
            interval: 5m
    install:
        createNamespace: true
        crds: CreateReplace
        remediation:
            retries: 3
    upgrade:
        crds: CreateReplace
        remediation:
            retries: 3
    values: {}
